# Generated by Django 3.1.1 on 2020-09-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationenglishrussian',
            name='russian_word',
            field=models.ManyToManyField(related_name='translations', to='dictionary.RussianWord'),
        ),
        migrations.AlterField(
            model_name='translationrussianenglish',
            name='english_word',
            field=models.ManyToManyField(related_name='translations', to='dictionary.EnglishWord'),
        ),
    ]
