# Generated by Django 3.1.1 on 2020-09-19 15:16

import dictionary.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=120, unique=True, validators=[dictionary.validators.only_english_character])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RussianWord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=120, unique=True, validators=[dictionary.validators.only_russian_character])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.IntegerField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionary.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslationRussianEnglish',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('english_word', models.ManyToManyField(to='dictionary.EnglishWord')),
                ('russian_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.russianword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.user')),
            ],
            options={
                'unique_together': {('user', 'russian_word')},
            },
        ),
        migrations.CreateModel(
            name='TranslationEnglishRussian',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.englishword')),
                ('russian_word', models.ManyToManyField(to='dictionary.RussianWord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.user')),
            ],
            options={
                'unique_together': {('user', 'english_word')},
            },
        ),
    ]
